GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImlhdCI6MTcwMDYwNjE3Nn0.wmv642zl6mKClMYl3MMplqMsfSmcVqJPf5M_JbM8Z8A


###

POST http://localhost:3000/login
Content-Type: application/json 

{
    "username": "John"
}