GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImlhdCI6MTcwMDYwNjEzM30.f7PJRu65hxOVICnkW7DfnGkWK9Ox5m9xIoDTZdK_A1E


###

POST http://localhost:3000/login
Content-Type: application/json 

{
    "username": "John"
}